### ISSUE TITLE
Write a blog post to announce new website and explain what it replaces

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/KeplerScienceWebsite#24]

**Comment by mrtommyb** [comment]
This is high priority

**Comment by barentsen** [comment]
I'm drafting one.  Will push after lunch.

**Comment by barentsen** [comment]
News article about new website posted and sync'ed to web.  Please review.

**Comment by kcolon** [comment]
I might move this one up to the second bullet but otherwise I think this post gets the point across:
information on the Campaign 9 microlensing experiment;


Should we say something in the post about being open to feedback on the new site from the community? Or would that just be opening a can of worms?
