### ISSUE TITLE
Update online target lists to include EPIC augmentation targets

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/KeplerScienceWebsite#64]
The [online target lists](http://keplerscience.arc.nasa.gov/k2-approved-programs.html) have no coords for the targets that are not in the EPIC, let's get these updated.

**Comment by kcolon** [comment]
I noticed that ExoFOP does not appear to include targets that do not have coordinates in our target lists.  For example, C6 should have 28,289 LC targets listed on ExoFOP but only 27,289 targets are on the ExoFOP (because only that many have coordinates in our list on the website). So EPIC 229227138 is not listed in the ExoFOP, for example.
