### ISSUE TITLE
Fix approved programs tables (C5 and C3) and fix the C1 target that Fleming brought up

### ISSUE THREAD

**Issue by kcolon** [KeplerGO/KeplerScienceWebsite#65]
Some C4 programs are listed at the top of the table in C5. There is also one program for C2 listed at the top of the C3 table.

http://keplerscience.arc.nasa.gov/k2-approved-programs.html#campaign-5

**Comment by barentsen** [comment]
The target list of C5 [1] contains program codes that start with "GO4". 

This is a minor annoyance because it is inconsistent with MAST. For example, the `Investigation ID` for EPIC 211390835 is `GO4100_LC` on our website, while it is linked to `GO5100` on MAST.  The title, abstract, program target list, etc is correct however.

To fix this we'd have to edit or re-create the target list [1], from which the website stuff can trivially be re-generated.

@mrtommyb how easy is it for you to re-create the target list for C2-3-4-5 to alter  this?  If the answer is "not easy", do you think it is worth our effort of editing the target list by hand to fix this, or do we just live with it.  I will await an executive decision.

[1] http://keplerscience.arc.nasa.gov/data/campaigns/c5/K2Campaign5targets.csv

**Comment by mrtommyb** [comment]
Geert, what was your workaround here?

**Comment by mrtommyb** [comment]
@kcolon fixed the C1 target list problem

**Comment by barentsen** [comment]
I hacked this into the script that creates the webpages:
```
+    def _correct_program_id(self, program_id):
 +        """Workaround for GitHub issue #65."""
 +        if self.campaign == "3" and program_id.startswith("GO2"):
 +            corrected_program_id = "GO3" + program_id[3:]
 +        elif self.campaign == "5" and program_id.startswith("GO4"):
 +            corrected_program_id = "GO5" + program_id[3:]
 +        else:
 +            corrected_program_id = program_id
 +        return corrected_program_id
```

This is bad because it doesn't fix the target list properly.

**Comment by mrtommyb** [comment]
ok, I've made changes with commit 6501990. Could you check that everything is good now?

**Comment by kcolon** [comment]
The proposal numbers are fixed but the programs are still listed out of order at the top of the tables :

http://keplergo.github.io/KeplerScienceWebsite/k2-approved-programs.html#campaign-5 <http://keplergo.github.io/KeplerScienceWebsite/k2-approved-programs.html#campaign-5>

Should we manually fix this?

**Comment by barentsen** [comment]
After I've removed the hack from my script, the order should fix itself.  I'll give it a go now.

**Comment by barentsen** [comment]
@mrtommyb Your commit fixed the problem for C5, but did not update the C3 target list.  Did you forget to `git add` it mayhaps?

**Comment by barentsen** [comment]
Tom committed the corrected C3 now.

I regenerated the program listings using the corrected target lists.

All looks good to me.
